### ISSUE TITLE
URI for NotificationsClient::replay() is incorrect.

### ISSUE THREAD

**Issue by tigerbook73** [PaddleHQ/paddle-php-sdk#102]
### Describe the bug

URI for NotificationsClient::replay() is incorrect.

    public function replay(string $id): string
    {
        $parser = new ResponseParser(
            $this->client->postRaw("/notifications/{$id}"),
        );
        ...
    }

According to API document, the URI shall be "/notifications/{$id}/replay".

### Steps to reproduce

Call the API to replay any notification. The return value is "".

### Expected behavior

Shall return new notification id.

### PHP version

PHP 8.1

### SDK version

paddle-php-sdk 1.20.1

### API version

Paddle verson 1

**Comment by mikeymike** [comment]
Hey @tigerbook73, thanks for raising this issue.

We'll be looking to get a fix out for this in out next patch release. Once updated we'll update this issue accordingly 👍

**Comment by davidgrayston-paddle** [comment]
Hi @tigerbook73 👋 

This issue has now been fixed and is included in release [v1.6.0](https://github.com/PaddleHQ/paddle-php-sdk/releases/tag/v1.6.0)
