### ISSUE TITLE
Provide payment-method related API

### ISSUE THREAD

**Issue by tigerbook73** [PaddleHQ/paddle-php-sdk#98]
### Please describe your feature request.

The payment-methods related API are not available in this package.

GET https://api.paddle.com/customers/{customer_id}/payment-methods
GET https://api.paddle.com/customers/{customer_id}/payment-methods/{payment_method_id}
DELETE https://api.paddle.com/customers/{customer_id}/payment-methods/{payment_method_id}

### Describe your solution.

Define and implement PaymentMethodClient class.

**Comment by davidgrayston-paddle** [comment]
Hi @tigerbook73 :wave:

Thank you for opening this issue, support for saved payment methods is currently being added in https://github.com/PaddleHQ/paddle-php-sdk/pull/97 and will be available soon

**Comment by davidgrayston-paddle** [comment]
Hello @tigerbook73 👋 

Payment method support is now available in latest release [v1.5.0](https://github.com/PaddleHQ/paddle-php-sdk/releases/tag/v1.5.0)
